### ISSUE TITLE
Could not run test using Singularity

### ISSUE THREAD

**Issue by yuifu** [marchoeppner/esga2#11]
### Description of the bug

```
Error executing process > 'NFCORE_GENOMEANNOTATOR:GENOMEANNOTATOR:AUGUSTUS_STAGECONFIG (config)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-augustus-3.4.0--pl5262h5a9fe7b_2.img.pulling.1666680659902 https://depot.galaxyproject.org/singularity/augustus:3.4.0--pl5262h5a9fe7b_2 > /dev/null
  status : 255
  message:
    FATAL:   Error making http request: Head "https://depot.galaxyproject.org/singularity/augustus:3.4.0--pl5262h5a9fe7b_2": x509: certificate has expired or is not yet valid: current time 2022-10-25T15:51:00+09:00 is after 2021-09-30T14:01:15Z




Pulling Singularity image https://containers.biocontainers.pro/s3/SingImgsRepo/biocontainers/v1.2.0_cv1/biocontainers_v1.2.0_cv1.img [cache /data2/harukao/projects/2018/stRamDA/results/20221025_test_genomeannotator/work/singularity/containers.biocontainers.pro-s3-SingImgsRepo-biocontainers-v1.2.0_cv1-biocontainers_v1.2.0_cv1.img.img]
```

### Command used and terminal output

```console
$ nextflow run nf-core/genomeannotator -r dev -profile test,singularity --outdir genomeannotator_test_002
```

### System information

- Nextflow version version 22.04.4 build 5706
- executor: local
- Hardware: HPC
- Container engine: Singularity
- OS: CentOS Linux 7

**Comment by aersoares81** [comment]
I'm also having problem with NFCORE_GENOMEANNOTATOR:GENOMEANNOTATOR:AUGUSTUS_STAGECONFIG. I even tried switching to conda (last resort, uh), but `Unknown configuration profile: 'conda'`.

```
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/genomeannotator] Pipeline completed with errors-
Error executing process > 'NFCORE_GENOMEANNOTATOR:GENOMEANNOTATOR:AUGUSTUS_STAGECONFIG (nfcore-pipeline)'

Caused by:
  Process `NFCORE_GENOMEANNOTATOR:GENOMEANNOTATOR:AUGUSTUS_STAGECONFIG (nfcore-pipeline)` terminated with an error exit status (127)

Command executed:

  mkdir -p augustus_config
  cp -R nfcore-pipeline/* augustus_config/

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_GENOMEANNOTATOR:GENOMEANNOTATOR:AUGUSTUS_STAGECONFIG":
      augustus: $(echo $(augustus  | head -n1 | cut -f2 -d " " | sed "s/[)]//" | sed "s/[(]//" ))
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 283: docker: command not found

Work dir:
  /projects/annotation/animal/nfcore-pipeline/work/5d/851bde6e400ec5f1db220b2d58e2bc

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out``
```

**Comment by Anbyya** [comment]
The error is because it is trying to copy symbolic link from the process of  stageconfig.nf under path genomeannotator/modules/local/augustus/stageconfig.nf, if you change the input type to val,     input:
    val augustus_config_dir, it works on my system, as it gives the absolute path instead of giving a broken symbolic link.

**Comment by marchoeppner** [comment]
Right, first of all, the initial issue sounds like a problem with the local system and/or installation of singularity. I am guessing this has been fixed by now (sorry, very late to the party)

The second thing - I will admit, I have no system available to play with docker; all of my development happens with Singularity. 

@aersoares81 I am assuming you are running this in a docker setting, but the pipeline apparently cannot find docker in the path of the executing node/system?

@Anbyya I would need a bit more context for this. Which version of nextflow was this? There is a bit of a complicated issue with modifying the repeatmasker database, which only seems to work if the object is a string rather than a file system object. I cannot really remember the details anymore, but took me a good while to get working.

**Comment by marchoeppner** [comment]
Closing this now - feel free to reopen if this is still a problem.
